# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Webserver-Source
version:      1.01
version_from: lib/Pod/Webserver/Source.pm
installdirs:  site
requires:
    Perl::Tidy:                    20031021
    Pod::Webserver:                3.02
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
